In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [10]:
data = pd.read_csv('/content/play_tennis.csv')
data.drop(columns=['day'],inplace=True)

In [11]:
data

     outlook  temp humidity    wind play
0      Sunny   Hot     High    Weak   No
1      Sunny   Hot     High  Strong   No
2   Overcast   Hot     High    Weak  Yes
3       Rain  Mild     High    Weak  Yes
4       Rain  Cool   Normal    Weak  Yes
5       Rain  Cool   Normal  Strong   No
6   Overcast  Cool   Normal  Strong  Yes
7      Sunny  Mild     High    Weak   No
8      Sunny  Cool   Normal    Weak  Yes
9       Rain  Mild   Normal    Weak  Yes
10     Sunny  Mild   Normal  Strong  Yes
11  Overcast  Mild     High  Strong  Yes
12  Overcast   Hot   Normal    Weak  Yes
13      Rain  Mild     High  Strong   No

In [12]:
# P(YES | Sunny,Cool,Normal,Weak)
# P(YES | Sunny,Cool,Normal,Weak) = P(Sunny | Yes)*P(Cool|Yes)*P(Normal|Yes)*P(Weak|Yes) * P(Yes)

In [ ]:
# What A naive Bayes Classifier do :
# 1. Training.
# 2. Create a LookUp Table or Dictionary.
# 3. Testing.

In [13]:
data['play'].value_counts()

play
Yes    9
No     5
Name: count, dtype: int64

In [14]:
P_yes = 9/14
P_no = 5/14

In [17]:
# OutLook
pd.crosstab(data['outlook'],data['play'])

play      No  Yes
outlook
Overcast   0    4
Rain       2    3
Sunny      3    2

In [28]:
Pyout_Over = 0
Pyout_Rain = 2/5
Pyout_Sunny = 3/5

Pnout_Over = 4/9
Pnout_Rain = 3/9
Pnout_Sunny = 2/9

In [29]:
# Temp
pd.crosstab(data['temp'],data['play'])

play  No  Yes
temp
Cool   1    3
Hot    2    2
Mild   2    4

In [30]:
Pytemp_Cool = 1/5
Pytemp_Hot = 2/5
Pytemp_Mild = 2/5

Pntemp_Cool = 3/9
Pntemp_Hot = 2/9
Pntemp_Mild = 4/9

In [31]:
# humidity
pd.crosstab(data['humidity'],data['play'])

play      No  Yes
humidity
High       4    3
Normal     1    6

In [32]:
Pyhum_High = 4/5
Pyhum_Normal = 1/5

Pnhum_High = 3/9
Pnhum_Normal = 6/9

In [33]:
# wind
pd.crosstab(data['wind'],data['play'])

play    No  Yes
wind
Strong   3    3
Weak     2    6

In [34]:
Py_wind_Strong = 3/5
Py_wind_Weak = 2/5

Pn_wind_Strong = 3/9
Pn_wind_Weak = 6/9

In [35]:
# P(YES | Sunny,Cool,Normal,Weak)
# P(YES | Sunny,Cool,Normal,Weak) = P(Sunny | Yes)*P(Cool|Yes)*P(Normal|Yes)*P(Weak|Yes) * P(Yes)

Pyes = Pyout_Sunny*Pytemp_Cool*Pyhum_Normal*Py_wind_Weak*P_yes
Pyes

0.0061714285714285725

In [36]:
Pno = Pnout_Sunny*Pntemp_Cool*Pnhum_Normal*Pn_wind_Weak*P_no
Pno

0.011757789535567312

In [ ]:
# Final Answer NO PLAY!!