<a href="https://colab.research.google.com/github/abhi01-sys/ML--Journey/blob/main/Reg_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [12]:
df = pd.read_csv('/content/house_prices_dataset.csv')

In [13]:
df

      square_feet  num_rooms  age  distance_to_city(km)          price
0     2248.357077          3   92             22.997972  200374.090410
1     1930.867849          2   22             13.984254  268784.847337
2     2323.844269          6   33             21.500945  315020.857676
3     2761.514928          3   63             10.343638  355111.468459
4     1882.923313          7   54             25.485200  234197.123903
...           ...        ...  ...                   ...            ...
9995  2650.551032          7    9             18.126034  431344.267823
9996  1000.827516          2   53             24.479692    6650.271134
9997  1647.341638          5   80              2.189312  233698.384301
9998  2247.882787          6   73             27.931014  280766.827379
9999  2322.194227          7   73             10.595721  342895.309114

[10000 rows x 5 columns]

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   square_feet           10000 non-null  float64
 1   num_rooms             10000 non-null  int64
 2   age                   10000 non-null  int64
 3   distance_to_city(km)  10000 non-null  float64
 4   price                 10000 non-null  float64
dtypes: float64(3), int64(2)
memory usage: 390.8 KB

In [15]:
df.isnull().sum()

square_feet             0
num_rooms               0
age                     0
distance_to_city(km)    0
price                   0
dtype: int64

In [16]:
X = df.drop('price', axis=1)
y = df['price']

In [18]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
from sklearn.linear_model import ElasticNet

In [23]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2 ,random_state=13)

In [35]:
lr = LinearRegression()
lr.fit(X_train,y_train)
y_pred = lr.predict(X_test)
r2_score(y_test,y_pred)

0.9593368061656841

In [42]:
reg = Ridge(alpha = 0.005)
reg.fit(X_train,y_train)
y_pred = reg.predict(X_test)
r2_score(y_test,y_pred)

0.9593368067124906

In [37]:
las = Lasso(alpha=800)
las.fit(X_train,y_train)
y_pred = las.predict(X_test)
r2_score(y_test,y_pred)

0.9593404929408251

In [44]:
Enet = ElasticNet(alpha=0.005,l1_ratio=0.254)
Enet.fit(X_train,y_train)
y_pred = Enet.predict(X_test)
r2_score(y_test,y_pred)

0.9593398661252736